image: ubuntu:14.04
before_script:
  - apt-get update -y
  - apt-get -y install gcc-mingw-w64 python cmake libxi-dev g++ libgl1-mesa-dev libglu1-mesa-dev

stages:
  - build
  - deploy

build:
  stage: build
  script:
    - cd linux_out
    - ./build
    - cd ../x86_64-w64-mingw32_out
    - ./build

deploy:
  stage: deploy
  script:
    - apt-get -y install ruby-dev
    - gem install dpl
    - mkdir -p out/bin/Linux
    - cp $(find linux_out/install -type f) out/bin/Linux/
    - mkdir -p out/bin/Windows
    - cp $(find x86_64-w64-mingw32_out/install -type f) out/bin/Windows/
    - zip get_image.zip $(find out/ -type f)
    - dpl --provider=releases --api-key=$GITHUB_RELEASES_API_KEY --repo=paulthomson/get-image --file=get_image.zip --release-number="v-$CI_BUILD_REF"

